FROM python:3.13-slim
WORKDIR /app
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
COPY pyproject.toml uv.lock ./
RUN uv sync --no-dev --frozen
COPY . .
EXPOSE 8080
CMD [".venv/bin/streamlit", "run", "ui.py", "--server.port=8080", "--server.address=0.0.0.0"]
